---
- hosts: all
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: Erstelle Ordner fuer VHost  
      file:
        path: "/var/www/vhosts/defaultwebsite"
        state: directory
        owner: www-data
        group: www-data
        mode: 0755
    - name: Kopiere Webseite
      copy:
        src: "index.html"
        dest: "/var/www/vhosts/defaultwebsite/index.html"
        owner: www-data
        group: www-data
        mode: 0644
  roles:
    - { role: ansible-role-apache }